### ISSUE TITLE
[Suggestion] Clicking on a command in the sidebar should run it

### ISSUE THREAD

**Issue by Explosion-Scratch** [alyssaxuu/slashy#8]
![image](https://user-images.githubusercontent.com/61319150/171777695-fe7804a0-aa0a-4290-8012-0ba23530caba.png)

Clicking on any of these commands doesn't actually run the command, even though all of the items have a pointer of cursor which suggests that they do

**Comment by alyssaxuu** [comment]
It might work for some commands, but others are contextual (require focus on the page somewhere to insert the content, for example). Maybe it could just append to the bottom of the page, unsure.

**Comment by Explosion-Scratch** [comment]
> It might work for some commands, but others are contextual (require focus on the page somewhere to insert the content, for example). Maybe it could just append to the bottom of the page, unsure.

Hmm, maybe just remove `cursor: pointer` from them then and add it to the buttons only?

**Comment by Explosion-Scratch** [comment]
I can see how this might be tricky to implement
